import React, { useState, useEffect, useCallback } from 'react';
import { useProject } from '@/shared/contexts/ProjectContext';
import { Button } from '@/shared/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shared/components/ui/tabs';
import { Film, LayoutGrid, Upload, ChevronDown, ChevronUp } from 'lucide-react';
import { GenerationRow } from '@/types/shots';
import { ReighLoading } from '@/shared/components/ReighLoading';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { InlineEditVideoView } from '../components/InlineEditVideoView';
import { useGenerations } from '@/shared/hooks/useGenerations';
import ImageGallery from '@/shared/components/ImageGallery';
import { useListShots } from '@/shared/hooks/useShots';
import { cn } from '@/shared/lib/utils';
import { useIsMobile } from '@/shared/hooks/use-mobile';
import { extractVideoPosterFrame } from '@/shared/utils/videoPosterExtractor';
import MediaLightbox from '@/shared/components/MediaLightbox/MediaLightboxRefactored';

const TOOL_TYPE = 'edit-video';
const TOOL_TYPE_NAME = 'Edit Video';

export default function EditVideoPage() {
  const { selectedProjectId } = useProject();
  const [selectedMedia, setSelectedMedia] = useState<GenerationRow | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [resultsPage, setResultsPage] = useState(1);
  const [showResults, setShowResults] = useState(true);
  const isMobile = useIsMobile();
  const { data: shots } = useListShots(selectedProjectId);
  
  // Lightbox state
  const [isLightboxOpen, setLightboxOpen] = useState(false);
  const [lightboxInitialMedia, setLightboxInitialMedia] = useState<GenerationRow | null>(null);
  
  // Fetch results generated by this tool (video variants)
  const {
    data: resultsData,
    isLoading: isResultsLoading,
  } = useGenerations(
    selectedProjectId || null,
    resultsPage,
    12,
    true,
    {
      variantsOnly: true, // Fetch from generation_variants table
      toolType: TOOL_TYPE, // Only show variants created by edit-video tool
      mediaType: 'video', // Only show video variants
      parentsOnly: true, // Exclude child variants
    }
  );
  
  // All results for lightbox navigation
  const allResults = (resultsData as any)?.items || [];
  
  // Navigate to previous/next in lightbox
  const handleNavigateLightbox = useCallback((direction: 'prev' | 'next') => {
    if (!lightboxInitialMedia || allResults.length === 0) return;
    const currentIndex = allResults.findIndex((m: any) => m.id === lightboxInitialMedia.id);
    if (currentIndex === -1) return;
    
    const newIndex = direction === 'prev' 
      ? (currentIndex - 1 + allResults.length) % allResults.length
      : (currentIndex + 1) % allResults.length;
    setLightboxInitialMedia(allResults[newIndex]);
  }, [lightboxInitialMedia, allResults]);

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (!files || files.length === 0) return;
    if (!selectedProjectId) {
      toast.error("Please select a project first");
      return;
    }

    setIsUploading(true);
    try {
      const file = files[0];
      
      if (!file.type.startsWith('video/')) {
        toast.error("Please upload a video file");
        return;
      }
      
      // Get current user ID for storage path
      const { data: { session } } = await supabase.auth.getSession();
      if (!session?.user?.id) {
        throw new Error('User not authenticated');
      }
      const userId = session.user.id;

      // Extract poster frame from video
      let posterUrl = '';
      try {
        const posterBlob = await extractVideoPosterFrame(file);
        const posterFileName = `edit-video/${userId}/${Date.now()}-poster.jpg`;
        const { error: posterError } = await supabase.storage
          .from('image_uploads')
          .upload(posterFileName, posterBlob, {
            cacheControl: '3600',
            upsert: false,
            contentType: 'image/jpeg'
          });
        
        if (!posterError) {
          const { data: { publicUrl } } = supabase.storage
            .from('image_uploads')
            .getPublicUrl(posterFileName);
          posterUrl = publicUrl;
        }
      } catch (posterError) {
        console.warn('[EditVideo] Poster extraction failed:', posterError);
      }
      
      // Upload video
      const fileExt = file.name.split('.').pop() || 'mp4';
      const fileName = `edit-video/${userId}/${Date.now()}.${fileExt}`;
      
      const { error: uploadError } = await supabase.storage
        .from('image_uploads')
        .upload(fileName, file, {
          cacheControl: '3600',
          upsert: false
        });

      if (uploadError) throw uploadError;

      const { data: { publicUrl: videoUrl } } = supabase.storage
        .from('image_uploads')
        .getPublicUrl(fileName);

      const { data: generation, error: dbError } = await supabase
        .from('generations')
        .insert({
          project_id: selectedProjectId,
          location: videoUrl,
          thumbnail_url: posterUrl || videoUrl,
          type: 'video',
          params: {
            prompt: 'Uploaded video',
            status: 'completed',
            is_uploaded: true,
            model: 'upload'
          }
        })
        .select()
        .single();

      if (dbError) throw dbError;

      setSelectedMedia(generation as any);

    } catch (error: any) {
      console.error("Upload error:", error);
      toast.error("Failed to upload video: " + error.message);
    } finally {
      setIsUploading(false);
    }
  };

  const isEditingOnMobile = selectedMedia && isMobile;

  return (
    <div className={cn(
      "w-full flex flex-col",
      isEditingOnMobile ? "min-h-[calc(100dvh-96px)]" : "h-[calc(100dvh-96px)]"
    )}>
      {!selectedMedia ? (
        <div className="w-full h-full px-4 overflow-y-auto">
          <div className="max-w-7xl mx-auto flex flex-col">
            <div className="flex flex-col md:flex-row bg-transparent" style={{ minHeight: '60vh' }}>
              {/* Left Panel - Placeholder */}
              <div 
                className="relative flex items-center justify-center bg-black w-full h-[20vh] md:w-[60%] md:h-auto md:flex-1 rounded-t-2xl md:rounded-t-none md:rounded-l-2xl overflow-hidden"
              >
               <div className="bg-background/90 backdrop-blur-sm rounded-lg border border-border/50 p-6 md:p-8 flex flex-col items-center justify-center space-y-4 md:space-y-6 max-w-md mx-4">
                  <div className="text-center space-y-1 md:space-y-2">
                    <h1 className="text-xl md:text-3xl font-light tracking-tight">Edit Videos</h1>
                    <p className="text-muted-foreground text-xs md:text-base hidden md:block">
                      Select a video from the right or upload a new one to regenerate portions.
                    </p>
                  </div>

                  <div className="relative w-full max-w-xs">
                    <input
                      type="file"
                      accept="video/*"
                      className="absolute inset-0 opacity-0 cursor-pointer z-10"
                      onChange={handleFileUpload}
                      disabled={isUploading}
                    />
                    <Button variant="outline" size="lg" className="w-full gap-2" disabled={isUploading}>
                      <Upload className="w-4 h-4" />
                      {isUploading ? "Uploading..." : "Upload Video"}
                    </Button>
                  </div>
               </div>
              </div>

              {/* Right Panel - Selection UI */}
              <div 
                className={cn(
                  "bg-background border-t md:border-t-0 md:border-l border-border overflow-hidden relative z-[60] flex flex-col w-full h-[50vh] md:w-[40%] md:h-auto rounded-b-2xl md:rounded-none md:rounded-r-xl"
                )}
              >
                 <VideoSelectionPanel 
                   onSelect={(media) => setSelectedMedia(media)} 
                 />
              </div>
            </div>
            
            {/* Results Gallery - Initial View */}
            {allResults.length > 0 && (
              <div className="mt-6 pb-6">
                <button 
                  onClick={() => setShowResults(!showResults)}
                  className="flex items-center gap-2 text-lg font-medium mb-4 hover:text-primary transition-colors"
                >
                  Edited Videos
                  {showResults ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  <span className="text-sm text-muted-foreground font-normal">
                    ({(resultsData as any)?.total || 0})
                  </span>
                </button>
                
                {showResults && (
                  <ImageGallery
                    images={allResults}
                    allShots={shots || []}
                    onImageClick={(media) => {
                      setLightboxOpen(true);
                      setLightboxInitialMedia(media as any);
                    }}
                    currentToolType={TOOL_TYPE}
                    currentToolTypeName={TOOL_TYPE_NAME}
                    itemsPerPage={12}
                    offset={(resultsPage - 1) * 12}
                    totalCount={(resultsData as any)?.total || 0}
                    onServerPageChange={setResultsPage}
                    serverPage={resultsPage}
                    showDelete={false}
                    showDownload={true}
                    showShare={false}
                    showEdit={false}
                    showStar={true}
                    showAddToShot={true}
                    enableSingleClick={true}
                  />
                )}
              </div>
            )}
          </div>
        </div>
      ) : (
        <div className="w-full px-4 overflow-y-auto" style={{ height: 'calc(100dvh - 96px)' }}>
          <div className="max-w-7xl mx-auto relative">
            <div className={cn(
              isEditingOnMobile ? "flex flex-col min-h-[60vh]" : "h-[70vh]"
            )}>
              <InlineEditVideoView 
                media={selectedMedia} 
                onClose={() => setSelectedMedia(null)}
                onVideoSaved={async (newUrl) => {
                  console.log("Video regenerated:", newUrl);
                }}
                onNavigateToGeneration={async (generationId) => {
                  try {
                    const { data, error } = await supabase
                      .from('generations')
                      .select('*')
                      .eq('id', generationId)
                      .single();
                    
                    if (data && !error) {
                      setSelectedMedia(data as any);
                    }
                  } catch (e) {
                    console.error("Failed to navigate to generation", e);
                  }
                }}
              />
            </div>
            
            {/* Results Gallery */}
            {allResults.length > 0 && (
              <div className="mt-6 pb-6">
                <button 
                  onClick={() => setShowResults(!showResults)}
                  className="flex items-center gap-2 text-lg font-medium mb-4 hover:text-primary transition-colors"
                >
                  Edited Videos
                  {showResults ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  <span className="text-sm text-muted-foreground font-normal">
                    ({(resultsData as any)?.total || 0})
                  </span>
                </button>
                
                {showResults && (
                  <ImageGallery
                    images={allResults}
                    allShots={shots || []}
                    onImageClick={(media) => {
                      setLightboxOpen(true);
                      setLightboxInitialMedia(media as any);
                    }}
                    currentToolType={TOOL_TYPE}
                    currentToolTypeName={TOOL_TYPE_NAME}
                    itemsPerPage={12}
                    offset={(resultsPage - 1) * 12}
                    totalCount={(resultsData as any)?.total || 0}
                    onServerPageChange={setResultsPage}
                    serverPage={resultsPage}
                    showDelete={false}
                    showDownload={true}
                    showShare={false}
                    showEdit={false}
                    showStar={true}
                    showAddToShot={true}
                    enableSingleClick={true}
                  />
                )}
              </div>
            )}
          </div>
        </div>
      )}
      
      {/* Media Lightbox */}
      {isLightboxOpen && lightboxInitialMedia && (
        <MediaLightbox
          media={lightboxInitialMedia}
          onClose={() => setLightboxOpen(false)}
          onNavigate={handleNavigateLightbox}
          showNavigation={allResults.length > 1}
          showTaskDetails={true}
        />
      )}
    </div>
  );
}

function VideoSelectionPanel({ onSelect }: { onSelect: (media: GenerationRow) => void }) {
  const { selectedProjectId } = useProject();
  const [activeTab, setActiveTab] = useState("gallery");
  const [shotFilter, setShotFilter] = useState<string>("all");
  const [currentPage, setCurrentPage] = useState(1);
  const [searchTerm, setSearchTerm] = useState("");
  const { data: shots } = useListShots(selectedProjectId);
  const itemsPerPage = 15;
  
  const {
    data: generationsData,
    isLoading: isGalleryLoading,
  } = useGenerations(
    selectedProjectId || null,
    currentPage,
    itemsPerPage,
    true,
    {
      shotId: shotFilter === 'all' ? undefined : shotFilter,
      mediaType: 'video', // Only show videos
      searchTerm: searchTerm.trim() || undefined
    } 
  );

  // Reset to page 1 when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [shotFilter, searchTerm]);

  return (
    <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col overflow-hidden">
      <div className="px-6 pt-2 border-b">
        <TabsList className="w-full justify-start bg-transparent p-0 h-auto gap-6">
          <TabsTrigger 
            value="gallery" 
            className="data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none px-2 py-3"
          >
            <LayoutGrid className="w-4 h-4 mr-2" />
            All Videos
          </TabsTrigger>
          <TabsTrigger 
            value="shots" 
            className="data-[state=active]:bg-transparent data-[state=active]:shadow-none data-[state=active]:border-b-2 data-[state=active]:border-primary rounded-none px-2 py-3"
          >
            <Film className="w-4 h-4 mr-2" />
            Shots
          </TabsTrigger>
        </TabsList>
      </div>

      <TabsContent value="gallery" className="flex-1 overflow-y-auto p-0 m-0 relative pt-4 px-4 md:px-6">
         {isGalleryLoading && !generationsData ? (
            <ReighLoading />
         ) : (
            <ImageGallery 
               images={(generationsData as any)?.items || []}
               onImageClick={(media) => onSelect(media as any)}
               allShots={shots || []}
               currentToolType={TOOL_TYPE}
               currentToolTypeName={TOOL_TYPE_NAME}
               showShotFilter={true}
               initialShotFilter={shotFilter}
               onShotFilterChange={setShotFilter}
               showSearch={true}
               initialSearchTerm={searchTerm}
               onSearchChange={setSearchTerm}
               initialMediaTypeFilter="video"
               showMediaTypeFilter={false} // Hide media type filter since we only want videos
               itemsPerPage={itemsPerPage}
               offset={(currentPage - 1) * itemsPerPage}
               totalCount={(generationsData as any)?.total || 0}
               onServerPageChange={setCurrentPage}
               serverPage={currentPage}
               showDelete={false}
               showDownload={false}
               showShare={false}
               showEdit={false}
               showStar={false}
               showAddToShot={false}
               enableSingleClick={true}
               hideBottomPagination={true}
            />
         )}
      </TabsContent>

      <TabsContent value="shots" className="flex-1 overflow-y-auto p-4 m-0">
        <ShotsVideoView onSelect={onSelect} />
      </TabsContent>
    </Tabs>
  );
}

function ShotsVideoView({ onSelect }: { onSelect: (media: GenerationRow) => void }) {
  const { selectedProjectId } = useProject();
  const { data: shots, isLoading } = useListShots(selectedProjectId);
  
  if (isLoading) return <ReighLoading />;

  // Filter shots to only show those with videos
  const shotsWithVideos = shots?.filter(shot => 
    shot.images?.some((img: any) => img.type === 'video')
  );

  return (
    <div className="space-y-8">
      {shotsWithVideos?.map((shot) => {
        const videos = shot.images?.filter((img: any) => img.type === 'video') || [];
        return (
          <div key={shot.id} className="space-y-3">
             <h3 className="font-medium text-lg flex items-center gap-2">
               {shot.name}
               <span className="text-xs text-muted-foreground font-normal">({videos.length} videos)</span>
             </h3>
             <ShotVideosRow videos={videos} onSelect={onSelect} />
          </div>
        );
      })}
      {(!shotsWithVideos || shotsWithVideos.length === 0) && (
         <div className="text-center py-10 text-muted-foreground">No shots with videos found.</div>
      )}
    </div>
  );
}

function ShotVideosRow({ videos, onSelect }: { videos: any[], onSelect: (media: GenerationRow) => void }) {
  if (!videos || videos.length === 0) return <div className="text-xs text-muted-foreground italic pl-2">No videos in shot</div>;

  return (
      <div className="flex gap-3 overflow-x-auto pb-4">
          {videos.map(video => (
              <div 
                key={video.id} 
                className="w-40 h-24 flex-shrink-0 relative cursor-pointer rounded overflow-hidden border border-border/50 hover:border-primary group"
                onClick={() => onSelect(video)}
              >
                  <img 
                    src={video.thumbnail_url || video.imageUrl || video.url || video.location} 
                    className="w-full h-full object-cover" 
                    alt="" 
                  />
                  {/* Video indicator */}
                  <div className="absolute inset-0 flex items-center justify-center bg-black/20 group-hover:bg-black/30 transition-colors">
                    <Film className="w-8 h-8 text-white/80" />
                  </div>
              </div>
          ))}
      </div>
  );
}

