-- Migration: Handle variant demotion - REMOVED TRIGGER APPROACH
--
-- Original plan: Add trigger when is_primary changes from true to false.
-- Problem: This fires during normal primary SWITCHES (promote B → demotes A),
-- and at that moment B's is_primary=true hasn't been committed yet, so the
-- trigger incorrectly thinks there's no primary and clears the generation.
--
-- Solution: Don't use a trigger. Instead, the demote_orphaned_video_variants RPC
-- handles the full cleanup directly (demote variant + clear generation).
-- This is the only case where we intentionally demote without promoting another.

-- No trigger needed - cleanup is done in the RPC
