-- Add upscaled_url column to generations table
-- This will store the URL to the upscaled version of the image when available

-- Add the upscaled_url column
ALTER TABLE generations 
ADD COLUMN upscaled_url text;

-- Add a comment to document the purpose
COMMENT ON COLUMN generations.upscaled_url IS 'URL to upscaled version of the image, generated by image-upscale task';

-- Create an index for faster queries when filtering by upscaled image presence
CREATE INDEX idx_generations_upscaled_url ON generations(upscaled_url) 
WHERE upscaled_url IS NOT NULL;

-- Verify the column was added
SELECT 'upscaled_url column added to generations table' as status;

