// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wczysqzxlwdndgxitrvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjenlzcXp4bHdkbmRneGl0cnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDI4NjgsImV4cCI6MjA2NzA3ODg2OH0.r-4RyHZiDibUjgdgDDM2Vo6x3YpgIO5-BTwfkB2qyYA";

// Install WebSocket instrumentation as early as possible
try {
  if (typeof window !== 'undefined') {
    const key = '__WS_PROBE_INSTALLED__';
    if (!(window as any)[key]) {
      (window as any)[key] = true;
      const OriginalWS = window.WebSocket;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (window as any).WebSocket = function(url: string, protocols?: string | string[]) {
        try { console.warn('[DeadModeInvestigation] WS new', { url, protocols }); } catch {}
        const ws = protocols ? new OriginalWS(url, protocols) : new OriginalWS(url);
        try {
          ws.addEventListener('open', () => console.warn('[DeadModeInvestigation] WS open', { url }));
          ws.addEventListener('error', () => console.warn('[DeadModeInvestigation] WS error', { url }));
          ws.addEventListener('close', (e) => console.warn('[DeadModeInvestigation] WS close', { url, code: (e as CloseEvent)?.code, reason: (e as CloseEvent)?.reason }));
        } catch {}
        return ws;
      } as any;
    }
  }
} catch {}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Faster auth token refresh for mobile
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true, // Required for OAuth redirects to work properly
  },
  global: {
    // Mobile-optimized HTTP settings
    fetch: (url, options = {}) => {
      const controller = new AbortController();
      // Longer timeout for edge functions (especially AI functions that can take 30+ seconds)
      // Storage uploads also need longer timeout for large files
      // Regular DB requests are still fast, but AI edge functions and storage uploads need more time
      const isEdgeFunction = url.includes('/functions/v1/');
      const isStorageUpload = url.includes('/storage/v1/object/');
      const timeoutMs = isEdgeFunction ? 60000 : (isStorageUpload ? 30000 : 8000); // 60s for edge functions, 30s for storage, 8s for other requests
      const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
      
      return fetch(url, {
        ...options,
        signal: controller.signal,
      }).finally(() => clearTimeout(timeoutId));
    },
  },
  db: {
    schema: 'public',
  },
});

// Auto-login for dev mode
if (import.meta.env.VITE_APP_ENV === 'dev') {
  const DEV_USER_EMAIL = import.meta.env.VITE_DEV_USER_EMAIL;
  const DEV_USER_PASSWORD = import.meta.env.VITE_DEV_USER_PASSWORD;
  
  if (DEV_USER_EMAIL && DEV_USER_PASSWORD) {
    supabase.auth.signInWithPassword({
      email: DEV_USER_EMAIL,
      password: DEV_USER_PASSWORD,
    }).then(({ error }) => {
      if (error) {
        console.error('Dev auto-login failed:', error);
      }
    });
  }
}

// Expose client globally for diagnostics and DeadMode investigation tooling
try {
  if (typeof window !== 'undefined') {
    (window as any).supabase = supabase;
  }
} catch {}

// Ensure Realtime socket always has a fresh auth token and nudge reconnects
try {
  supabase.auth.onAuthStateChange((event, session) => {
    try {
      (supabase as any)?.realtime?.setAuth?.(session?.access_token ?? null);
      (supabase as any)?.realtime?.connect?.();
      console.warn('[DeadModeInvestigation] Realtime auth sync', {
        event,
        hasToken: !!session?.access_token,
        timestamp: Date.now()
      });
      
      // Trigger heal on SIGNED_IN events (occurs on tab resume)
      if (event === 'SIGNED_IN' && typeof window !== 'undefined') {
        setTimeout(() => {
          try {
            console.warn('[DeadModeInvestigation] Dispatching auth-heal');
            window.dispatchEvent(new CustomEvent('realtime:auth-heal'));
          } catch {}
        }, 1000); // Delay to let auth settle
      }
    } catch (e) {
      console.warn('[DeadModeInvestigation] Realtime auth sync failed', e);
    }
  });
} catch {}