// This file is automatically generated. Do not edit it directly.

// CRITICAL: Log at the VERY TOP before any imports
console.info('[ReconnectionIssue] 🔥 CLIENT.TS FILE LOADED AT:', new Date().toISOString());

// EMERGENCY: Check if app is in infinite loop state
console.error('[EMERGENCY] 🚨 CLIENT.TS STARTUP CHECK:', {
  timestamp: Date.now(),
  hasWindow: typeof window !== 'undefined',
  visibilityState: typeof document !== 'undefined' ? document.visibilityState : 'unknown',
  userAgent: typeof navigator !== 'undefined' ? navigator.userAgent.slice(0, 50) : 'unknown'
});

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, __IS_DEV_ENV__, __WS_INSTRUMENTATION_ENABLED__, __REALTIME_DOWN_FIX_ENABLED__, __CORRUPTION_TRACE_ENABLED__ } from '@/integrations/supabase/config/env';
import { installWindowOnlyInstrumentation } from '@/integrations/supabase/instrumentation/window';
import { installRealtimeInstrumentation } from '@/integrations/supabase/instrumentation/realtime';
import { InstrumentationManager } from '@/integrations/supabase/instrumentation/InstrumentationManager';
import { captureRealtimeSnapshot } from '@/integrations/supabase/utils/snapshot';
import { __CORRUPTION_TIMELINE__ } from '@/integrations/supabase/utils/timeline';
import { initAuthStateManager } from '@/integrations/supabase/auth/AuthStateManager';
import { getReconnectScheduler } from '@/integrations/supabase/reconnect/ReconnectScheduler';
import { maybeAutoLogin } from '@/integrations/supabase/dev/autoLogin';

// Initialize InstrumentationManager and install window-only instrumentation BEFORE any client creation
InstrumentationManager.initialize();
installWindowOnlyInstrumentation();

// Log environment detection
console.info('[DevEnvCheck] 🔍 Environment Detection:', {
  VITE_APP_ENV: (import.meta as any)?.env?.VITE_APP_ENV,
  hostname: typeof window !== 'undefined' ? window.location?.hostname : 'no-window',
  __IS_DEV_ENV__,
  __WS_INSTRUMENTATION_ENABLED__,
  __REALTIME_DOWN_FIX_ENABLED__,
  __CORRUPTION_TRACE_ENABLED__,
  timestamp: Date.now()
});

// CRITICAL: Log before Supabase client creation
console.info('[ReconnectionIssue] 🚨 SUPABASE CLIENT INITIALIZATION:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  env: (import.meta as any)?.env?.VITE_APP_ENV,
  timestamp: Date.now()
});

let supabase: ReturnType<typeof createClient<Database>>;

try {
  console.info('[ReconnectionIssue] 🔥 ATTEMPTING TO CREATE SUPABASE CLIENT...');
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
    realtime: {
      params: { eventsPerSecond: 10 },
      heartbeatIntervalMs: 30000,
      reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 10000),
    },
    global: {
      fetch: (url: string, options: RequestInit = {}) => {
        const isEdgeFunction = url.includes('/functions/v1/');
        const isStorageUpload = url.includes('/storage/v1/object/');
        const isAuthRequest = url.includes('/auth/v1/');
        const isRestRequest = url.includes('/rest/v1/');
        if (!isEdgeFunction && !isStorageUpload) {
          // Sample logging: only log 1 in 20 requests to reduce noise
          const shouldLog = Math.random() < 0.05;
          if (shouldLog) {
            console.info('[ReconnectionIssue] Allowing unlimited time for auth/rest request:', { url, isAuthRequest, isRestRequest });
          }
          const startTime = Date.now();
          return fetch(url, options).then(
            (response) => {
              const duration = Date.now() - startTime;
              if (shouldLog) {
                console.info('[ReconnectionIssue] Auth/rest request succeeded:', { url, duration, status: (response as any).status });
              }
              return response;
            },
            (error) => {
              const duration = Date.now() - startTime;
              // Always log errors, but sample success/start logs
              console.error('[ReconnectionIssue] Auth/rest request failed:', { url, duration, error: (error as any).message, name: (error as any).name });
              throw error;
            }
          );
        }
        const controller = new AbortController();
        const timeoutMs = isEdgeFunction ? 60000 : 30000;
        const timeoutId = setTimeout(() => {
          console.warn('[ReconnectionIssue] Aborting request due to timeout:', { url, timeoutMs });
          controller.abort();
        }, timeoutMs);
        let composedSignal = controller.signal;
        if ((options as any).signal && 'signal' in options && (options as any).signal instanceof AbortSignal) {
          const existingSignal = (options as any).signal as AbortSignal;
          const composedController = new AbortController();
          const onAbort = () => composedController.abort();
          controller.signal.addEventListener('abort', onAbort);
          existingSignal.addEventListener('abort', onAbort);
          composedSignal = composedController.signal;
        }
        return fetch(url, { ...options, signal: composedSignal }).finally(() => clearTimeout(timeoutId));
      },
    },
    db: { schema: 'public' },
  });
  console.info('[ReconnectionIssue] 🔥 SUPABASE CLIENT CREATED SUCCESSFULLY!');
} catch (error: any) {
  console.error('[ReconnectionIssue] ❌ SUPABASE CLIENT CREATION FAILED:', error);
  console.debug('[DeepDebug] 🔍 CLIENT CREATION ERROR DETAILS:', { errorMessage: error?.message, errorType: typeof error, errorConstructor: error?.constructor?.name, errorStack: error?.stack?.split('\n').slice(0, 5), timestamp: Date.now() });
  throw error;
}

// Expose client globally for diagnostics
try {
  if (typeof window !== 'undefined') {
    (window as any).supabase = supabase;
  }
} catch {}

// Initialize centralized reconnect scheduler
getReconnectScheduler();

// Initialize centralized auth state manager
initAuthStateManager(supabase);

// Install realtime instrumentation after client creation
installRealtimeInstrumentation(supabase);

// Dev auto-login
maybeAutoLogin(supabase);

export { supabase };

// CRITICAL: Top-level logs for everything (retain)
console.info('[ReconnectionIssue] 🔥 SUPABASE CLIENT EXISTS:', !!supabase);
console.info('[ReconnectionIssue] 🔥 REALTIME EXISTS:', !!(supabase as any)?.realtime);
console.info('[ReconnectionIssue] 🔥 SOCKET EXISTS:', !!(supabase as any)?.realtime?.socket);
console.info('[ReconnectionIssue] 🔥 SOCKET STATE:', (supabase as any)?.realtime?.socket?.readyState);


